- src/aiori-MPIIO.c
- src/ior.c
IOR was leaking a hint structure in MPI-IO case, two groups in
common code, and when we get the info member from the file we were
losing our reference to the hints we just passed in.
> clean up MPI resources

- src/ior.c
tidy up a few stray memory allocations.  Note: these changes make
HumanReadable no longer re-entrant.
> assorted memory leak cleanups

- configure.ac
Commit aa604c1d38de803aa0db3f3abb5515e0ed1857ea introduced gpfs_fcntl
operations, depending if gpfs.h and gpfs_fcntl.h were found.  These
routines need the GPFS client library.  This configure check will bring
in libgpfs -- you will still need to set LDFLAGS and CPPFLAGS if gpfs is
installed in some non-default locaiton (as it is on Blue Gene).
fixes https://github.com/chaos/ior/issues/15
> Add gpfs libraries if needed

- configure.ac
Some environments (notably, Cray Linux) seem to provide only the dynamic versions of libgpfs despite static compilation being the default.  This causes autoconf to detect gpfs.h but fail when libgpfs.a can't be linked.  This change just gives an escape hatch for such systems (NERSC Edison/Cori and ALCF Theta, for example)
> add an explicit --without-gpfs

- src/parse_options.c
Read-only tests using the MPI-IO interface were failing because `IOR_CREAT` was being carried over from the default settings defined in `init_IOR_Param_t`, resulting in this error:
MPI_FILE_OPEN(119): Cannot use MPI_MODE_CREATE or MPI_MODE_EXCL with MPI_MODE_RDONLY , (aiori-MPIIO.c:145)
This explicitly unsets `IOR_CREAT` (and `IOR_EXCL`, just as good measure) so read-only tests with MPI-IO work again.
> explicitly disable O_CREAT and O_EXCL when doing read-only test

- configure.ac
- doc/USER_GUIDE
- src/aiori-POSIX.c
- src/ior.c
- src/ior.h
- src/parse_options.c
Support includes tuning the following parameters:
- Number of stripe targets (numTargets)
- Chunk size
Support is enabled if BeeGFS API header files are found during the configure step.
> add support for tuning BeeGFS parameters

- src/ior.c
- src/ior.h
- src/parse_options.c
The patch extends stonewalling with a wear out phase introducing two new options:
-y This enables together with -D N the stonewalling to N seconds however, once write out is complete, it does continue to writeout data on all processes that not reached the maximum number of tuples written
-1 N Forces to access a maximum of N segments with the same parameters, useful if data has been written.
Example:
Write, stonewalling max 10 segments, stonewall timer -D == 0 seconds (for testing):
mpiexec -np 2 ./src/ior -v -y -w -D 0 -b 10m -s 10 -t 10m -k
0: stonewalling pairs accessed globally: 10 this rank: 10
1: stonewalling pairs accessed globally: 10 this rank: 5
So process 1 will now do additional 5 iterations...
Read: this one reads only 5 segments back, normally one would do 10 iterations. …
> StoneWalling with WearOutPhase

- contrib/cbif.c
- src/mdtest.c
The MacOS doesn't support lseek64 and open64. So when compiling IOR in MacOS will cause error "Undefined symbols for _lseek64 and _open64" in file contrib/cbif.c.
> fix a bug when make IOR in MacOS will cause a compile error 

- configure.ac
Previously, the configure script could fail to find an MPI
implementation but continue regardless. This alters the behaviour so
that the configure script fails if the check for MPI does.
> Hardens test for MPI

- src/aiori-NCMPI.c
From Pnetcdf 1.7, the MPI datatype corresponding to NC_BYTE  is change from MPI_BYTE to MPI_SIGNED_CHAR. If not change, running IOR with NCMPI will cause a fatal error as below:
ERROR in aiori-NCMPI.c (line 287): cannot write to data set.
ERROR: NetCDF: Not a valid data type or _FillValue type mismatch.
> change MPI_BYTE to MPI_SIGNED_CHAR

- src/mdtest.c
Add previously removed call to **realpath** to initialize the path variable.
See issue #28 for a discussion.
> initialize path variable correctly

- src/utilities.c
The O_DIRECT option was not working as set_o_direct_flag() were moved to
utilities.c but there the  #define _GNU_SOURCE where missing. This lead
to the Warning "cannot use O_DIRECT".
> Fix O_DIRECT option

- src/ior.c
IOPS accounting should work with stonewall as well since now we calculate the results based on actual bytes transferred.
Signed-off-by: Li Dongyang <dongyangli@ddn.com>
> Add OPs result columns back

- configure.ac
- src/Makefile.am
- src/aiori-MMAP.c
- src/aiori-POSIX.c
- src/aiori.c
- src/aiori.h
- src/ior.c
- src/ior.h
It shares the create/open/delete/set_version/get_file_size
functions with POSIX backend.
The mmap backend also supports fsync and fsyncPerWrite options,
and it will use msync() instead and fsync().
Signed-off-by: Li Dongyang <dongyangli@ddn.com>
Fixes: #45
> Add mmap as a new AIORI backend

- src/aiori-MPIIO.c
MPI requires all ranks to refer to the same file within the communicator passed to MPI_File_open.
This bug was exposed during testing with Open MPI and BeeGFS.  Without it, a run produces an error like the following:
srun -N2 -n4 ./install/bin/ior -a MPIIO -b 10MB -t 1MB -v -F -w -o /p/bscratcha/moody20/IOR_MANUAL
<snip>
Commencing write performance test: Wed May 16 13:22:31 2018
[catalyst105:75531] [1]mca_sharedfp_lockedfile_file_open: Error during file open
[catalyst106:37197] [2]mca_sharedfp_lockedfile_file_open: Error during file open
[catalyst106:37198] [3]mca_sharedfp_lockedfile_file_open: Error during file open
> use MPI_COMM_SELF when opening file to get file size in MPIIO

- src/aiori-MPIIO.c
- src/ior-output.c
- src/ior.c
- src/ior.h
- src/mdtest.c
- src/parse_options.c
- src/test/lib.c
- src/utilities.c
This patch fixes most of the warnings caused
by unused variables and assignments from incompatible
type.
> Fix warnings reported at compilation time

- configure.ac
- src/aiori-NCMPI.c
- src/aiori-POSIX.c
gcc-7.3 did not like prototype and definition of NCMPI_GetVersion having different arguments
newer lustre will say "including lustre_user.h directly is deprecated", so feel free to have the same configure tests I used in ROMIO.
> More fixes

- src/parse_options.c
Context: IOR gets a segfault if an unsupported API string
is provided.
This patch checks that the I/O backend is supported, otherwise
IOR stops with an error.
> Check provided IO API is valid

- src/aiori.c
- src/aiori.h
- src/ior.c
- src/ior.h
- src/mdtest-main.c
Context: IOR initializes all available backends. If one
backend fails to initialize IOR cannot be used.
This patch makes IOR initialize only the backends
which will be used. The initialization is done after
that the parameters are checked so that the help message
can still be dispayed is something goes wrong.
> Initialize only the required backends

- src/ior-output.c
- src/ior.c
- src/ior.h
- src/iordef.h
Context: write and read results from the same iteration
use the same length value in Bytes. When stonewalling is
used the size variates depending on the performance of
the access. This leads to wrong max bandwidths reported
for writes as shown in the following example:
write     10052      ...
read      9910       ...
write     10022      ...
read      9880       ...
write     10052      ...
read      9894       ...
Max Write: 9371.43 MiB/sec (9826.66 MB/sec)
Max Read:  9910.48 MiB/sec (10391.89 MB/sec)
>  Fix erroneous reported write bandwidth with stonewalling

- src/aiori-DUMMY.c
- src/aiori-HDF5.c
- src/aiori-HDFS.c
- src/aiori-IME.c
- src/aiori-MPIIO.c
- src/aiori-NCMPI.c
- src/aiori-POSIX.c
- src/aiori-RADOS.c
- src/aiori-S3.c
- src/aiori.c
- src/aiori.h
- src/mdtest.c
- src/parse_options.c
Context: Some backends may have used different names in
the past (like IME backend use to be IM). Legacy scripts
may break.
This patch adds a legacy name option in the aiori structure.
Both name and legacy name work to select the interface.
But the following warning is printed if the legacy name is used:
ior WARNING: [legacy name] backend is deprecated use [name] instead.
> Support old legacy name in backends

- configure.ac
- doc/sphinx/userDoc/options.rst
- src/aiori-HDF5.c
- src/ior.h
- src/parse_options.c
In HDF5-1.10 the library has an option to read and write the metadata of a file collectively.  One has to opt-in to this optimization with a property list but particularly at large scale it can have tremendous performance implications.
Further information:
- https://support.hdfgroup.org/HDF5/docNewFeatures/CollMDataIO/RFC-CollectiveMetadataReads.pdf
- https://support.hdfgroup.org/HDF5/doc/RM/RM_H5P.html#Property-SetAllCollMetadataOps
> HDF5: option to enable collective metadata

- src/ior.c
This stops the segfault that gets triggered when an invalid API is specified in the configfile (technically fixes #95), but it doesn't address the bigger bug indicated in #98.
Even if #98 isn't resolved in the short term, I'd like to put this into master so it can go into the 3.2 release.  I'd rather have a documented known issue than a segfault.
> stop the segfault when an invalid api is specified in configfile

- src/parse_options.c
Context: IOR outputs errors when the '-w -W' flags are used
without '-r'. Write a file using with check write option
should be possible even without setting read.
This patch fixes a condition which was introduced for
HDFS to remove RDWR flag in some particular cases.
Write check was set with the write only flag but it
requieres the read flag.
> Make write verification work even without read test

- src/aiori-IME.c
- src/ior.c
This patch adds the support of `rmdir/mkdir` syscalls into the IME backend (feature supported starting from IME 1.3).
In addition, this patch fixes an issue in function PrependDir(), which bypasses the backend's implementation of `rmdir/mkdir`.
> IME: add support of mkdir/rmdir into the IME backend

- src/mdtest.c
IOR uses the `GetTimeStamp()` wrapper (in src/utilities.h) to allow `gettimeofday()` to be used for timings instead of `MPI_Wtime()` to calculate throughput. This commits adds the same logic to mdtest timings. By default `MPI_Wtime()` is still used. If `_NO_MPI_TIMER` is added to, e.g., src/utilities.h `gettimeofday()` is used instead.
Having this possibility is important because `MPI_Wtime()` is known to report wrong timings on some Xeon architectures when used with OpenMPI-2.0.2 for instance ([see here for further explanation of this issue](https://stackoverflow.com/questions/42270974/mpi-wtime-timer-runs-about-2-times-faster-in-openmpi-2-0-2)), resulting in compromised mdtest throughput.
> mdtest: Use GetTimeStamp() instead of MPI_Wtime()

- configure.ac
- src/aiori-DUMMY.c
- src/aiori-MMAP.c
- src/aiori.c
- src/ior.c
- src/mdtest.c
- src/option.c
- src/parse_options.c
- travis-test.sh
This patch enables correct compilation on both MacOS and Linux using only POSIX.1-2008-compliant C with XSI extensions.  It also changes the travis build to explicitly use `-std=c99` to catch noncompliant patches going forward.
This does _not_ require a user compile with strict POSIX conformance though, and the general expectation is that most users will continue to build with various GNUisms enabled by default (and in fact, this is required to compile with `--with-lustre`).  The intent here is just to curb any creeping dependence on a specific libc or compiler.
resolves #93
> compile correctly with -std=c99

- src/mdtest.c
Currently, calculation for barriers case looks a bit
suprising, for example, Min stats is from min of
Max value of number of mpi proc, this makes Min
and Max very similar in our testing thus we get
a small Std value too.
I am not a MPI expert, but question is why we
don't use more nature calcuation which calculate
all results from different iterations and MPI proc?
Signed-off-by: Wang Shilong <wshilong@ddn.com>
> mdtest: fix calculation for barriers

- configure.ac
- src/aiori-POSIX.c
Fix the configure check if --with-lustre is specified, but
the linux/lustre/lustre_user.h header is not present.  Only
one of the headers needs to be included if both are found.
In some cases, FASYNC is not defined, but forms part of the
O_LOV_DELAY_CREATE value, add a #define in that case.
Fix quoting in MPI check to avoid upsetting syntax highlighting.
Fixes #115.
Fixes: cb88c4c19a831d94b864c49a162e2635730540e5
Signed-off-by: Andreas Dilger <adilger@dilger.ca>
> lustre: fix checks for lustre_user.h header

- src/ior.h
This bugfix fixes a previously introduced bug of the HDF5 plugin when refactoring.
> Bugfix for HDF5 plugin; readded collective_md.

- src/parse_options.c
optarg contains a NULL address, which causes a segfault in
NodeMemoryStringToBytes().
> Fix segfault with option memoryPerNode

- src/aiori-POSIX.c
Use existing output file if it has the desired stripe settings
(number of targets, chunk size)
This fixes the problem of being unable to create the output if multiple instances write to the same file.
> beegfs: don't fail if output exists

- src/aiori-POSIX.c
- src/aiori.h
- src/mdtest.c
Add new option '-k' to support file creation test with mknod,
which is widely used in lustre.
Signed-off-by: Gu Zheng <gzheng@ddn.com>
> add mknod support

- doc/USER_GUIDE
- src/aiori-NCMPI.c
Function ncmpi_get_file_info was first introduced in
PnetCDF version 1.2.0. Check PnetCDF library version,
so printing MPI-IO hints can be enabled for NCMPI.
> showHints: allow NCMPI to print I/O hints

- src/ior.c
- src/ior.h
- src/mdtest.c
- src/parse_options.c
- src/utilities.c
- src/utilities.h
If you look at the differences, they appear like a lot but the overwhelming majority are merely cleaning up output messages in mdtest.  It used to have at least 3 lines for every output message because it wrapped each one up in a if branch testing for verbosity.  I added a helper function so now it is just one line of code for each output message.
There there is also a new function added in utilities which prints the node map (a 0 or 1 for every rank where 0 means on a different node from rank 0 and 1 means same node) which also returns whether the node/task mapping is round-robin or contiguous.
Then a small change in mdtest to shift by ppn if contiguous or 1 otherwise.  It used to only shift by 1 so it used to only work when the mapping was round robin.  Now it works for both.
Then a …
> Fixed shift.  Also cleaned up output messages

- src/ior-output.c
- src/ior.c
- src/mdtest.c
MDTest and IOR can output the performance when hitting the stonewall.
Also allow to output rate and tp for mdtest.
> Feature stonewall perf report

- src/ior-output.c
- src/ior.c
- src/mdtest.c
That branch allows to use the -X parameter for MDTest which verifies that the data read (with -e) is the expected pattern.
MDTest does already check that the bytes read are the right number of bytes, but not 
(Note: build upon the feature-mdtest-timer branch)
> Feature verify mdtest

- src/aiori-POSIX.c
- src/mdtest.c
- src/test/lib.c
Fixing some memory leaks :)
Found via gcc's `-fsanitize=address` sanitizer. (There are more, but that's what I catched so far ;) )
> Fix Some Memory Leaks

- src/utilities.c
Fix a memory violation when run in serial.
Found via gcc's `-fsanitize=address` sanitizer.
> Fix: Heap Buffer Overflow

- src/aiori-POSIX.c
Fix bug introduced in #170.
Cannot get a good hold on the memory lifetime of the parsed options and the memory leaks they introduce. So I just leave them as is.
> Fix Last Free

- doc/USER_GUIDE
- src/aiori-DAOS.c
- src/aiori-DFS.c
- src/ior-internal.h
- src/ior-output.c
- src/ior.c
IOR currently reports IOPS in the summary but doesn't report it per iteration. This patch adds IOPS numbers for each iteration in the output. IO Latency is also important to look at, especially for small transfer sizes. We report that too for each iteration.
- Latency reported is computed by taking the average latency of
all ops from a single task, then taking the minimum of that
between all tasks.
- IOPS is computed by taking the total number of ops across all
tasks divided by the total access time to execute those ops.
> IOR: Add latency and IOPS numbers to each iteration.

- src/ior.c
ior -R should memset the buffer being read, otherwise a read that does nothing will report success in the data verification phase.
> fix -R option to do proper data verification

- .gitignore
- configure.ac
- doc/mdtest.1
- src/Makefile.am
- src/mdtest.c
that is, delete inherited striping layout with the invocation of a command line parameter during command execution. Feature is made available only when running configure and building with the "with-lustre" option.
> Enable global default dir layout for subdirs in Lustre

- src/aiori-POSIX.c
- src/aiori.h
- src/mdtest.c
Context: mknod does not return a file descriptor.
> Fix confusing output of mknod

- configure.ac
Enables running without setting LD_LIBRARY_PATH
Uses DT_RUNPATH (--enable-new-dtags) so that it can
be overwritten by setting LD_LIBRARY_PATH should
libraries be moved.
If this can't be landed, it would be great if someone
with autoconf experience could make any changes
to make it conditional.
Signed-off-by: Jeff Olivier <jeffrey.v.olivier@intel.com>
> Add runpath to configure script for daos and cart

- src/aiori-RADOS.c
This param is no longer present and breaks the build when using --with-rados
Signed-off-by: Mark Nelson <mnelson@redhat.com>
> src/aiori-RADOS: Remove Direct IO option check.

- src/aiori-DAOS.c
- src/aiori-DFS.c
- License should inherit from IOR License.
- remove checksums from Array API
- add DFS dir oclass option
> DAOS Driver: Update License & Align with 1.0 API changes

- configure.ac
- src/Makefile.am
- src/aiori-CEPHFS.c
- src/aiori.c
- src/aiori.h
- src/ior.c
- src/ior.h
This is a new aiori backend using libcephfs that is loosely based on the existing POSIX and RADOS backends.  It also borrows the "prefix" concept from the DFS backend for an existing POSIX mount point (necessary for ior/mdtest to function properly even when using a library for direct filesystem access).  A slight change to libcephfs.h is needed for IOR to properly compile (this does not appear to be necessary for C++ clients using libcpehfs however):
```
#include <sys/time.h>
```
io500 tests on a 10 node in-house test cluster with 2X replication and co-located clients appeared to function properly with similar (though much better in the case of sequential reads) scores vs using the POSIX backend with kernel based CephFS mount points.  In the following results, the mdtest easy directories …
> [RFC] src/aiori-CEPHFS: New libcephfs backend

- src/ior.c
Display host names when using the -j argument (outlierThreshold) so
that IOR could help to better identify slow nodes:
WARNING: for client02, task 6, write elapsed transfer time is 65.738326
> Display outlier host names

- src/aiori-CEPHFS.c
Fixes io500 C application invocation of the aiori-CEPHFS backend so long as the API is set in the individual benchmark sections rather than globally.  It also throws a WARN if Init is called before the options are initialized (which is what IO500 tries to do currently if you set the API globally in the ini file).
> src/aiori-CEPHFS: Option warnings, shutdown checks, and cmount nullification

- src/mdtest.c
`mdtest --posix.odirect` was not working and failed with "Invalid argument" on write/read (e.g. on RHEL7 for xfs/BeeGFS/NFS), because the corresponding memory buffers for write/read were not correctly aligned. According to `man 2 open`, "The O_DIRECT flag may impose alignment restrictions on the length and address of user-space buffers". This patch fixes DirectIO support by allocating page-aligned write and read buffers via `posix_memalign`.
> mdtest: allocate aligned buffers to support DirectIO

- src/mdtest.c
As discussed with @johnbent  and @glennklockwood, new PR to fix a typo in initial posix_memalign commit for DirectIO support (`write_bytes` -> `read_bytes`)
> mdtest: use correct number of bytes for posix_memalign of read buffer

- src/Makefile.am
- src/mdtest.c
Read now always checks the first byte/8 bytes for the signature (item number).
This should increase the robustness again broken systems.
Added also --verify-write option which performs a read immediately after a write. Supports #206
> MDTest changed verification pattern. 

- src/Makefile.am
- src/aiori-S3-4c.c
- src/ior.c
- src/ior.h
This pull request updates the S3-aws4c implementation to the new AIORI interface and outsources the options into module-specific options.
An example usage is:
./ior -a=S3-4c --S3-4c.user=julian --S3-4C.host=localhost:9000
Credentials need to be stored in $HOME/.awsAuth, e.g.:
julian:accesskey:secretkey
Using the minio server as documented in testing/s3.sh
leads to an error:
CURL call failed at aiori-S3-4c.c, line 1258
ERROR: 411 '411 Length Required'
Which may be due to missing part in the XML. As the implementation and used library maybe a bit outdated, further checks are necessary.
> Fix s3-4c implementation

- src/aiori-HDF5.c
- src/aiori-MPIIO.c
- src/aiori.h
- the hints structure was not getting initialized in MPIIO when HDF5
backend is used. Since HDF5 utilizes the MPIIO backend, this causes
a segfault.
> HDF5: fix segfault in HDF5 driver after latest AIORI changes

- src/aiori-IME.c
ime_initialized global variable is not reset after having called ime_native_finalize.
> aiori-IME: Fix init after finalize issue

- src/ior.c
Hi,
I got some invalid JSON format output of IOR results with using `-i N (N > 1)` option, 
so I fix it in this commit.
small test result by `jsonlint` command bellow:
```sh
$ ior -i 2 -O summaryFormat=JSON -O summaryFile=$(pwd)/testIOR.json -b 1m -t 128k
$ jsonlint testIOR.json
testIOR.json:149:4: Warning: Object contains duplicate key: 'segmentCount'
|  At line 149, column 4, offset 3858
|  Object started at line 133, column 4, offset 3472
testIOR.json:150:4: Warning: Object contains duplicate key: 'blockSize'
|  At line 150, column 4, offset 3882
|  Object started at line 133, column 4, offset 3472
testIOR.json:151:4: Warning: Object contains duplicate key: 'transferSize'
|  At line 151, column 4, offset 3909
|  Object started at line 133, column 4, offset 3472
testIOR.json:180:4: …
```
> Fix JSON output format of IOR using repeating option

- src/Makefile.am
- src/aiori-POSIX.c
- src/ior.c
- src/md-workbench-main.c
- src/md-workbench.c
- src/md-workbench.h
- src/parse_options.c
- src/utilities.h
This patchseries integrates the md-workbench benchmark into this benchmark test suite by porting the object-based API to AIORI and converting other bits and pieces as needed.
The plan is to transform a few more pieces of the code using IOR typical code and then to convert the tool to an API similar to MDTest and IOR.
The MD-Workbench differs from MDTest by providing means to benchmark performance of interactive users that do different operations.
Here is a paper about it:
https://hps.vi4io.org/_media/research/publications/2019/dlumlwmkm19-understanding_metadata_latency_with_mdworkbench.pdf
> Feature: md-workbench

- src/aiori-S3-libs3.c
The file mapping created object names such as:
out00file1
out00file2
...
out00file11
From the source filename:
./out/0_0/file-1
Without bucket mapping, this caused the deletion of ./out/0_0/file-1 to delete objects such as out00file11.
Now the filenames map / to _ and are all suffixed with "-" 
example: _out_00_file1-
This prevents the issue as there is no common suffix.
> Bugfix S3: suboptimal name mapping was leading to accidential deletes in md-workbench.

- src/mdtest.c
This PR refactors the 50+ static variables to be part of a global option structure to remove ambiguity in which scope the variable is.
In the code, there is at the moment too much dependency to global variables.
Ultimately, the goal was to make stonewalling work with the multi-dir approach but it turned out this requires much more refactoring and therefore, doing it piece by piece.
> Refactoring: MDTest

- src/mdtest.c
Fix the bug reported by Rick to increase clarity. Thanks!
The previous offset calculation when using multiple iterations was:
for (i = start; i < stop; i++) // i = table position == test number
for (k=0; k < size; k++) 
for (j = 0; j < iterations; j++) 
value = all[(k \* tableSize \* iterations) + (j*tableSize) + i];
Note that the mean and min/max was then computed over these values.
But as the values were stored in memory in the order:  iteration, rank, table
the correct term is: value = all[j \* tableSize \* size + k * tableSize + i];
Assume iterations = 2 and size = 3, the value for the test i=0 was computed from:
all[0 * 2 *tbl + 0 * tbl] = 0tbl
all[0 * 2 *tbl + 1 * tbl] = 1tbl
all[1 * 2 *tbl + 0 * tbl] = 2tbl
all[1 * 2 *tbl + 1 * tbl] = 3tbl
all[2 * 2 *tbl + 0 * tbl] = 4tbl
all[2 * 2 …
> Bugfix MDTest calculation of multiple iterations was incorrect.

- src/mdtest.c
When code was refactored to eliminate global vars, there was a reference to unique_dir_per_task that was not updated.  This only affects builds using --with-lustre.
> mdtest: fix reference to unique_dir_per_task for builds --with-lustre

- configure.ac
- src/aiori-DFS.c
- remove un-needed libdaos_common lib since DAOS driver was removed
- use default container object class when it's not specified
> DFS: make use of collective open to share file handle

- src/aiori.c
- src/ior-internal.h
- src/ior.c
- src/ior.h
- src/parse_options.c
- src/utilities.c
- src/utilities.h
- testing/basic-tests.sh
- testing/test_comments.ior
This series of patches addresses #219.
The behavior of the offset creation had been changed as follows:
- there is no need to create the array of all file offsets any more
- for sequential IO, the offset calculation is part of the loops
- for random IO, the random offset calculation is done as before but only within *one* block providing some meaning to the semantics of block, transfer size, and segments. Before the blocks were meaningless for random.
Now: the segments repeat the same random pattern.
Consider the example for 1 process:
-t 4096 -b 40960 -s 2
There are 10 random positions between offsets 0, 4k, up to 36k, this pattern is repeated two times (offset by 40kb in the second iteration).
When more than 1 process takes place, it depends on if it is file per process or shared file. …
> Fix offset integration

- src/ior.c
- src/ior.h
The calculation in the API was missleading.
Average across processes vs. total = sum.
> Fix calc stonewall

- src/aiori-debug.h
Assigning MPI_STATUS to a local variable and then referring to the
local will ensure that the same value is used in both the conditional
expression and the call to MPI_Error_string.
Otherwise, when MPI_STATUS is a function call, like
MPI_CHECKF(fubar(), "%s", "error in fubar");
fubar() is called twice.  If there are underlying intermittent errors,
the error code/message for the first call is lost, with confusing output
like this:
read      2206.18    17.27      145.93      262144     131072
0.272595   291.88     0.290829   292.41
ERROR: cannot access explicit, noncollective, MPI MPI_SUCCESS: no errors, (aiori-MPIIO.c:451)
> Do not execute functions twice in MPI_CHECKF

- src/aiori-DFS.c
ior now expects stat to not be fatal. update the DFS driver to not
exit if stat fails since the file can simply not exist.
> aiori-DFS: stat should not be fatal

- src/mdtest.c
A reproducer wasn't included with #281 so I haven't tested to make sure this is complete, but the patch in #281 seemed pretty straightforward.
This should resolve #298.
> fix #281 ("MDTest calculation of multiple iterations was incorrect") for 3.3 release branch

- src/mdtest.c
Allow to store stonewall information when running with multiple dirs, e.g. to save at most 10000 files in a directory, one may use:
$ mdtest -n 1000000 -I=10000 -t -w 3901 -e 3901 -P -N 1 -F  -x stonewall.dat -C -Y -W 1 -a POSIX
$ mdtest -n 1000000 -I=10000 -t -w 3901 -e 3901 -P -N 1 -F -x stonewall.dat -C -a POSIX -r
Note that stonewall allows storing ONLY full directories in the granularity of -I specified.
This was a missing patch to previous changes.
> Fix MDTest multidir option to work with stonewall file.

- src/ior.c
This was a (newly introduced) bug that could trigger endless loops for stonewalled workloads.
> Bugfix ior stonewalling case.

- src/ior.c
IOR by default outputs the numbers of errors.
Reason: The number of error messages can be overwhelming, particularly in a parallel program (Gigabytes...).
One -v increases the verbosity level to provide the extra details without adding too many other messages.
> IOR: move verbose output of detailed errors to verbosity level 1.

- src/aiori-DFS.c
- src/aiori-S3-4c.c
- src/ior.c
- src/ior.h
- src/md-workbench.c
- src/mdtest.c
- src/parse_options.c
- src/parse_options.h
- src/utilities.c
- src/utilities.h
- testing/complex-tests.sh
Trying to reduce the global variables.
There was a code section in DistributeHints where the MPI_COMM_WORLD was used.
> Refactoring: remove global comm_world communicator from utilities.c

- src/ior-output.c
- src/ior.c
- src/utilities.c
- src/utilities.h
Remove time adjustment as measurements are relative anyway.
> Remove MPI timer in favor of gettimeofday() to prevent MPI timing issues. 

- src/md-workbench.c
- src/mdtest.c
- src/utilities.c
- src/utilities.h
Add rank into I/O buffer to make individual files unique.
1) Before the reduce was missing, thus if any other rank than 0 encounters errors, then these were not counted.
2) Include the rank number into each value to make each file pattern unique.
3) Accelerate comparison using 64-bit type
4) Allow adding user-specified number (allowing to distinguish multiple runs) defeating dedup of previous runs.
> MDTest data verification improvements.

- src/mdtest.c
- src/mdtest.h
when using the --saveRankPerformanceDetails=<FILE> option.
The CSV isn't perfectly formatted, yet, contains a bit much information.
> MDTest allow storing information per rank for later analysis 

- src/mdtest.c
- src/mdtest.h
Reporting per rank now outputs the performance of the individual rank (before the barrier), the iteration throughput includes the barrier time (if not -B=0 is set). 
Before, it was the time after the barrier.
Bugfix also the calculation of the standard deviation which now applies to iteration.
Example:
The following will use the DUMMY plugin which needs 1000us per create/access but only on Rank 0 of two Ranks for two iterations:
$ mpiexec -np 2 --oversubscribe  ./src/mdtest -n 1000 -i 2 -a DUMMY   --saveRankPerformanceDetails=test.csv   --dummy.delay-only-rank0 --dummy.delay-create=1000  -w 1024 -e 1024 --dummy.delay-xfer=1000 -B=0 -P 
```
SUMMARY rate: (of 2 iterations)
Operation         per Rank: Max            Min           Mean       per Iteration: Max            Min           Mean …
```
> Improve and fix the reporting in MDTest. 

- src/option.c
Context: Options with values are not properly parsed.
If the value is not set, a bug makes appear that 0 was
provided.
This patch fixes options parsing (issue #337). An error
is reported if 'backend.option=' argument is provided.
> Fix detection of option with empty value

- src/aiori-MPIIO.c
- src/ior.c
Fixes  #340 
MPI-IO's treatment of noncontiguous is probably a lot different from the other drivers --- I don't even know what noncontiguous S3 access would mean for example.
I don't know why it was disabled a year ago, but this removes the hard error upon requesting it and fixes a memory allocation problem when using it:
$ mpiexec -np 4 ./src/ior --mpiio.useFileView --mpiio.showHints --mpiio.useStridedDatatype \
-s 4 -b 1M -t 1M -c -a MPIIO -o testfile1
There is presently no way to know from the output if the benchmark ran noncontig or contig (one could infer if the "useFileView" information was part of the output summary)
> Make noncontiguous I/O work again

- src/mdtest.c
> reset test comm to world comm since it can be used in finalize callbacks.

- src/aiori-DUMMY.c
Example usage:
ior -a DUMMY --dummy.delay-create=10000 --dummy.delay-close=100000 --dummy.delay-xfer=20000
> Dummy plugin, add delay for close and sync.

- src/ior.c
https://github.com/hpc/ior/blob/03f72b4b7ca32597ded6f9b69b0ee4e7125cfa10/src/ior.c#L1688
https://github.com/hpc/ior/blob/03f72b4b7ca32597ded6f9b69b0ee4e7125cfa10/src/ior.c#L1764
https://github.com/hpc/ior/blob/03f72b4b7ca32597ded6f9b69b0ee4e7125cfa10/src/ior.c#L1771
https://github.com/hpc/ior/blob/03f72b4b7ca32597ded6f9b69b0ee4e7125cfa10/src/ior.c#L1825
https://github.com/hpc/ior/blob/03f72b4b7ca32597ded6f9b69b0ee4e7125cfa10/src/ior.c#L1832
In expression `i * test->numTasks`, both operands are **int** type.
It will overflow 32 bits when the `segmentCount` and `numTasks` are large enough.
> IOR: fix overflow in offset calculations

- src/mdtest.c
When running mdtest create + read, fileperproc is set properly so
the driver known it's not a single shared file. But when mdtest is
running with only read (-E) with a pre-existing dataset, fileperproc
is never set, and driver thinks it's a single shared file and can
do optimization to share the file handle.
> mdtest: make sure fileperproc is set for mdtest read

- src/mdtest.c
Fixes #381 
Upstream pull request #311 (https://github.com/hpc/ior/pull/311) added support
for bencmarking directory renames, inserting an extra entry into the list of
MDTEST operations, but missed updating some existing uses.
This change fixes the remaining uses, to correct misleading ops/sec messages.
> Fix off-by-one error in verbose ops/sec messages.

- src/aiori-HDF5.c
- src/aiori-POSIX.c
- src/iordef.h
- src/md-workbench.c
- src/mdtest.c
- src/parse_options.c
- src/utilities.c
This branch supports full block scrambling using the [golden prime method implemented in elbencho](https://github.com/breuner/elbencho/blob/master/source/toolkits/random/RandAlgoGoldenPrime.h#L39).  I verified that the resulting file is much less compressible than the "incompressible" data packet type.  For example, writing a 1 MiB file in 4 KiB blocks, then gzipping it (default parameters) results in the following compressed sizes:
- 10772 bytes for `-l incompressible` in ior-3.3
- 11470 bytes for `-l incompressible` in master (commit a436395)
- 1045698 bytes for `-l random` in this branch
There is a lot missing from this branch so far:
I opened this WIP PR just so I don't lose track of progress here.
> WIP: randomized datapackettype

- src/test/example.c
This PR simply fixes the example.c file, which seems to have been using an older version of `init_IOR_Param_t` that did not require an MPI communicator.
> fixed example used in make check

- src/aiori-CEPHFS.c
This MR makes three contributions:
1. Port CEPHFS to current AIORI API, as it was not compiling anymore. (#393be78)
2. Add Lazy I/O support via a new, optional `--cephfs.olazy` flag. (#1e34b3e)
3. Add a remote mount prefix option. This is necessary for multi-tenancy users such as OpenStack Manila, where the root filesystem is not being mounted, but a volume subpath (our remote_prefix option) is mounted instead. (#53eb94f)
Notably, enabling Lazy I/O enables much better performance for single shared file collective I/O (IO500's ior hard mode):
With `--ceph.olazy`:
```
Summary of all tests:
Operation   Max(MiB)   Min(MiB)  Mean(MiB)     StdDev   Max(OPs)   Min(OPs)  Mean(OPs)     StdDev    Mean(s) Stonewall(s) Stonewall(MiB) Test# #Tasks tPN reps fPP reord reordoff reordrand seed segcnt …
```
> Port CEPHFS module to current AIORI API, add Lazy I/O support, and Manila support.

- src/aiori-CEPHFS.c
Unless I misunderstood the way AIORI works, it seems that `OPTION_REQUIRED_ARGUMENT` is not a per-module setting, but is global.
Therefore switch these options that were as REQUIRED to OPTIONAL. Otherwise, `ior` refuses to run, even when not using `-a CEPHFS`, unless these cephfs-specific options are provided.
The cephfs module does have a check in the initialization function to verify whether some argument that it requires are present or not, so this should be fine.
BTW, some grepping revealed that the same issue might also be present for the RADOS module.
> bugfix: CEPHFS: Make all module parameters optional

- src/test/Makefile.am
Without this patch, command "make check" fails when LDFLAGS environment
variable is set at configure.
> use AM_LDFLAGS instead of LDFLAGS

- configure.ac
- doc/USER_GUIDE
- doc/sphinx/userDoc/options.rst
- src/aiori-HDF5.c
- src/aiori-HDFS.c
- src/aiori-IME.c
- src/aiori-MMAP.c
- src/aiori-MPIIO.c
- src/aiori-NCMPI.c
- src/aiori-POSIX.c
- src/aiori-S3-libs3.c
- src/aiori-aio.c
- src/aiori-debug.h
- src/ior-output.c
- src/ior.c
- src/md-workbench.c
- src/mdtest.c
- src/parse_options.c
Hi everyone,
Looking to contribute some improvements to IOR which cover:
- Updated documentation to include some of the newer options in or near the information which I newly added for Lustre
- Improved the HDF5 backend so it is able to flush files to disk (`-e` option) and print file hints (`--hdf5.showHints` option); a controversial change might be the removal of version macro checks for old HDF5 version (10+ years)
- Unify naming and usage of debug macros (`WARN`, `INFO`, `ERR`, and associated ones) across all files in the repository which did not only eliminate some compiler warnings but should have fixed some bugs in format strings
- Rename `mpiio.*` options in NCMPI backend to `ncmpi.*`
- Replace `MPI_CHECK` with `NCMPI_CHECK` where appropriate
- Remove duplicate `.get_options = …
> Update Documentation, Improve HDF5 Backend, Unify Debug Macros

- src/aiori-debug.h
Hi again,
In a comment to the last merge commit cbedd6afddb241790a0fdc126ea8d205d9bb3cf7 it was noted that one of the previous changes introduced an unbalanced multi-line comment due to a missing `*/` at the end of a line. This pull request just fixes this issue.
I am sorry that a second pull request is required to fix the prior introduced issue. Guess that shows you can never have enough compilers to test an implementation against 😃
Best,
Christian
> Fixes missing termination of multi-line comment

- src/aiori-DFS.c
When using the new API with container labels, use the label to destory
the container as that doesn't have to be a uuid.
> aiori/DFS: fix an issue when destorying a container

- src/mdtest.c
Barrier option should be on by default; however currently it's not called
since the barrier is in a prologue check.
> mdtest: fix barrier option

- configure.ac
This PR adds an option to the config script to build IOR with Darshan. The user can use `--enable-darshan` and provide an installation prefix to their Darshan shared library. The script modifies `LDFLAGS` to add the necessary flags and checks if the library exists.
IOR allows a very flexible micro benchmarking with different parameters. Together with Darshan, this can provide a very useful analysis with fine-grained I/O traces to explain performance. I am currently developing an I/O library and using IOR to quantify the performance characteristics. However, it is not possible to `LD_PRELOAD` the same functions twice, for this reason, a Darshan enabled IOR proves extremely useful to my current work and can benefit developers in similar situations.
> Add option to link IOR to Darshan

- src/ior.c
- src/ior.h
- src/parse_options.c
Allow running IOR with a minimum runtime by repeating the current pattern from the beginning of the file. That means in a write that didn't complete until a certain deadline, the file will be over-written from the beginning.
Especially useful when you want to enforce a runtime for (random) reads.
Example usage:
$ mpiexec -np 4 ./src/ior -O minTimeDuration=1 -D=2 -O stoneWallingWearOut=1 -k
> IOR: allow minimum runtime. Compatible with stonewall

- src/aiori-POSIX.c
- src/mdtest.c
- src/mdtest.h
This fixes the verification of POSIX and mdtest.
Before: POSIX driver called ERR aborting when an error is detected.
New behavior: continue but output error message
> Bugfix: mdtest-verification, posix tolerate short read

- configure.ac
- src/aiori-POSIX.c
Update --posix.gpfs.finegrainreadsharing hint with latest optimizations
in IBM Spectrum Scale - 5.1.4 for small strided reads from a shared
file in a parallel application.
Fixes https://github.com/hpc/ior/issues/418
Signed-off-by: Pidad D'Souza <pidsouza@in.ibm.com>
> aiori-POSIX: Spectrum Scale finegrainreadsharing performance updates

- src/aiori-S3-libs3.c
Dear maintainers,
please consider this small convenience extension. It allows to specify a list of S3 hosts instead of only one host. Hosts can be separated by any of [ ,;]. At runtime every rank will pick one of the given hosts in a round robin fashion. 
This will allow scaling the total bandwidth against a set of S3 servers without a load balancer. It has been tested against MinIO in a distributed server configuration.
I tried not to mess with ior's architecture and think I put the addition in the right spot. Still, let me know if you'd prefer something slightly different.
Best, Andreas
> Allow list of S3 hosts

- src/aiori-HDF5.c
This is currently innocuous since MPIIO_Delete returns early on dry runs, but might be a problem if something changes in the future.
> HDF5 Backend - fix dry run return fall-through in HDF5_Delete

- src/aiori-HDF5.c
The new Subfiling Virtual File Driver in HDF5 uses MPI internally, so it's useful to be able to have HDF5 cleanup and finish MPI operations before IOR calls MPI_Finalize.
> HDF5 Backend - add HDF5_Finalize routine to call H5close

- configure.ac
- doc/USER_GUIDE
- src/aiori-POSIX.c
- src/aiori-POSIX.h
- src/mdtest.c
Add below option to mdtest to optimize performance on IBM Spectrum Scale version later than 5.1.5.
createsharing : This hint optimizes the performance of workloads that
create many files in a shared directory
Fixes https://github.com/hpc/ior/issues/435
Signed-off-by: Pidad D'Souza <pidsouza@in.ibm.com>
> mdtest: Add new IBM Spectrum Scale createsharing hint

- src/aiori-RADOS.c
- src/ior.h
This PR contains the following fixes/updates for the RADOS backend for IOR:
* sync module API prototypes to current aiori interface
* errno.h must be included
* add init/finalize routines to setup/teardown RADOS cluster outside of typical I/O paths
> RADOS backend fixes/updates

- src/aiori-RADOS.c
* convert required args to optional
* use check_params function to check user input and avoid errors
> relax required args for RADOS backend

- src/md-workbench.c
md-workbench compilation fails on a clean Ubuntu docker image because the size of `struct timespec` is unknown. This just fixes that by specifying we are coding to a version of POSIX C that defines `struct timespec`.
This bug goes back to the last IO500 tag upon which an upcoming ior-4.0.0 release will be based per #361.
> strictly required to use struct timespec

- doc/sphinx/userDoc/tutorial.rst
At least on my system with a case-sensitive file system, ./IOR won't do any good.
> lowercase ./ior in tutorial

- doc/sphinx/userDoc/scripts.rst
I noticed IOR END being mentioned in the user documentation about scripting. There is IOR STOP instead.
Furthermore, those control words are parsed case-insensitively, which perhaps should be noted.
Which I did.
Please merge at your leisure.
> userDoc: fix mentioning of IOR STOP and be more specific about case

- src/ior.c
If the '-E' option is not used and existing output files are found, the current error message says that the files will be "overwritten" but this is not totally accurate.  Without '-E' the file will be deleted first, which makes a difference if the files were precreated with a specific layout.
Update the error to report that files will be deleted in this case.
> ior: improve error for existing output file

- configure.ac
- src/Makefile.am
- src/aiori-FINCHFS.c
- src/aiori.c
- src/aiori.h
This change introduces a new abstract I/O interface for FINCHFS file system, which is available at
https://github.com/tsukuba-hpcs/finchfs
> ADIO for FINCHFS

- src/aiori-DFS.c
DAOS 2.0 is out of support and not deployed anywhere, so remove legacy code support for that.
> aiori-dfs: cleanup old and unsupported DAOS code

- src/ior.c
- src/ior.h
- src/mdtest.c
- src/mdtest.h
- src/parse_options.c
- src/utilities.c
- src/utilities.h
This branch allows to store per-operation information from mdtest and IOR by using the savePerOpDataCSV option.
One file is created per rank so beware, it can be huge!
The timing per operation is stored for up to 1M values per rank and then flushed to the CSV file. 
Do not store the CSV files on the same storage as the one you are testing.
It does support #463 a bit, by allowing to later extract time intervals as needed.
> Feature latency

- src/aiori-DFS.c
O_EXCL should not be used on dfs_open() if not instructed to use it explicitely.
Otherwise, it fails when using -E as follows:
ERROR (aiori-DFS.c:675): 2: 17: dfs_open() of foo.00000002 Failed
03/19/2024 15:44:27: Process 2: FAILED in TestIoSys, Cannot create file
Abort(1) on node 2 (rank 2 in comm 496): application called MPI_Abort(comm=0x84000004, 1) - process 2
> Add support for params->useExistingTestFile to DFS backend

- src/utilities.h
At least the IO500 compiles IOR with `-Werror=strict-prototypes`, the missing `void` in the argument list causes a compilation error. This commit fix this.
> Fix strict-prototype error

- src/mdtest.c
Expose the directory rename phase via:
$ mdtest -D -C -U   -n 10
See #483
To see it working, test for instance with:
$ strace -f ./src/mdtest -D -C -U   -n 10 2>&1 | grep -i "mdtest"
> Expose rename phase via -U flag.

- src/aiori-CEPHFS.c
Re-enable mdtest for the CephFS aiori backend.
> src/aiori-CEPHFS: re-enable mdtest support.

- src/aiori-POSIX.c
- src/aiori-POSIX.h
- src/mdtest.h
To fix https://github.com/hpc/ior/issues/491 I've updated the Lustre pool functionality to make it more robust, particularly on systems where the Lustre API is not being used or when people are building without specific lustre functionality.
> Fixing issue raised in issue 491 by previously added Lustre pool functionality

- src/mdtest.c
When time is printed in the summary (option -Z), then display units should be time-per-op, instead of hard coded ops-per-second.
Before change:
SUMMARY time (in ops/sec): (of 1 iterations)
After:
SUMMARY time (in ms/op): (of 1 iterations)
> mdtest: fix time units in summary

- src/aiori-aio.c
- src/ior.c
This commit fixes two issues:
- The AIO backend prints the max outstanding transactions when starting. This is printed by every MPI rank and doesn't add much. Probably is left over from some debugging.
- Init MPI ***before*** parsing the command line. Without this every rank thinks it is rank 0 so messages that should only be printed by rank 0 are printed n times.
> Fix a couple of minor issues with IOR output

- src/ior-output.c
- src/ior.c
> Bugfix JSON format. Avoid redundant output with low verbosity level.

- src/mdtest.c
The -f/-l options are used to restrict the number of tasks mdtest runs to smaller subsets of the total size specified via the job MPI parameters.
In this mode a subset of the ranks will not participate in the test, and those ranks have to be managed properly so they join up with the ranks that did at the end.
The recently refactored logic fixed one issue but created another in the corner case of size > first == last. In this scenario only one rank participates in the test, but all ranks were duping MPI_COMM_WORLD and the barrier behavior was not correct for this scenario resulting in a hang.
This solves the problem by making the logic common (a new group and communicator will always be created for the test whether it is for all ranks or a subset) and ensuring that any ranks which aren't …
> fix(#506): mdtest size > first == last hang

- src/ior.c
As explained in the putenv(3) man page, putenv() places the string pointer passed in directly into the environment - no copy.
Given that the hint array is allocated on the stack, this will definitely corrupt the environment. Should use setenv(3) instead, which copies strings.
> Fix wrong usage of putenv()

- src/aiori-MPIIO.c
Bugfix for #514, the changes are explained in the last paragraph there. ("To fix this, I changed MPI_INT to MPI_BYTE in get elements and removed the multiplication with the size.")
> bugfix for #514 about xferBytes miscalculation

- src/aiori-LIBNFS.c
The function nfs_open2 on create already propagates the desired attributes, thus not need for an extra nfs_chmod call.
> libnfs: remove redundant chmod call on create

- src/utilities.c
There was a loophole in the code when rank != 0 but another communicator was used, e.g. in IO500.
> Bugfix for node detection with multi-communicators.
