hpc/ior

src/aiori-HDF5.c, src/aiori-NCMPI.c, src/utilities.c
Cleaning out my branches: here are some small improvements.   
* the 'resultString' fix simply makes the compiler happier.  
* the hint file parsing problem bit one of my collaborators.
=> Housekeeping

src/aiori-MPIIO.c
Context: Some file systems require a prefix in the path.
The POSIX 'access' call fails and consequently files are
never deleted.
This patch implements an access function in the MPIIO
backend using MPI_File_open. Prefixes can now be parsed
by ROMIO.
=> Implement an access function for MPIIO backend

src/Makefile.am, src/aiori-IME.c
Fix compilation of aiori backends requiring external libraries and add support for new function calls in the IME backend.
=> Fix compilation of some aiori backends and add new function calls in IME backend

src/aiori-HDF5.c, src/aiori-NCMPI.c
The pnetcdf changes fix build failures.  
The HDF5 changes clean up resources in more error cases.
=> Pnetcdf fixes

src/aiori-HDF5.c, src/aiori-MPIIO.c, src/aiori-POSIX.c, src/ior-output.c, src/ior.h, src/parse_options.c
Mitigates #85 by providing a --dryRun option
=> Dry-run option to test the configuration / scripts.

src/aiori-DUMMY.c, src/aiori-MMAP.c, src/aiori-POSIX.c, src/aiori.c, src/aiori.h, src/ior-output.c, src/ior.c, src/ior.h, src/mdtest.c, src/option.c, src/option.h, src/parse_options.c, src/utilities.c, src/utilities.h, testing/test_comments.ior
Maybe the option handling deserves some discussion; This branch is the superset of 139.
=> Moving options to submodules

.travis.yml
=> Travis CI: Fix HDF5 Build

src/aiori-MPIIO.c, src/aiori-POSIX.c, src/ior.c, src/iordef.h
Includes ERRF, WARNF, and MPI_CHECKF format string macros.
=> Added some extra debug.

configure.ac, src/Makefile.am, src/aiori-Gfarm.c, src/aiori.c, src/aiori.h, src/ior.c
This change introduces a new abstract I/O interface for Gfarm file system.
=> abstract I/O interface for Gfarm file system

src/option.c
=> add break that was accidentally removed earlier

src/aiori-DFS.c
=> update DFS driver with new DAOS API changes.

configure.ac
=> fix config error with older autoconf/automake versions.

configure.ac, src/aiori-DFS.c
- Update configure check for DAOS to check for libs under daos_dir/lib64
- Add DFS option for the dfs prefix
=> DAOS driver update

src/aiori-IME.c
This patch adds the support of sync (flush client page cache
for all opened files) and mknod in the IME backend.
=> aiori-IME: Add support of sync and mknod in IME backend

configure.ac, src/aiori-DFS.c
- Update config to look for cart in lib and lib64
- Use a collective dfs_mount between all ranks rather than independent
=> DFS driver update to share DFS mount on init

src/aiori-DFS.c
=> dfs: add DFS sync call

src/aiori-CEPHFS.c
Add sync wrapper similar to fsync.
Signed-off-by: Mark Nelson <mnelson@redhat.com>
=> src/aiori-CEPHFS: Add sync

src/aiori-DAOS.c, src/aiori-DFS.c
=> update DFS and DAOS drivers to new aiori module interface.

src/aiori-IME.c
This patch updates IME backend to support new aiori interface.
It also fixes some indentation issues.
=> aiori-IME: Update to new aiori interface

src/aiori-DAOS.c
=> remove comm from get size cb in DAOS driver

configure.ac, src/Makefile.am, src/aiori-MMAP.c, src/aiori-POSIX.c, src/aiori-POSIX.h, src/aiori-aio.c, src/aiori.c, src/aiori.h, src/mdtest.c, src/option.c, src/option.h
This merge adds a driver for the Linux AIO interface.
=> Feature aio

configure.ac, src/ior.c, src/utilities.c
Add configure macros to detect which code to use for detection for CPU socket count. 
#245
=> Detection of system features for number of sockets #245

src/aiori-POSIX.c, src/ior-output.c
=> POSIX GFPS adjusted to new API #248

src/ior-output.c
Hi,
IOR documents that the `summaryFormat` option could be `[default,CSV,JSON]`.
While the default and json output works, I miss some output for the CSV option.
This commit adds CSV output for IOR.
The output will just include the values of the `Results` section.
All other sections are omitted, since it's hard to produce a useful csv
with all information included.
As an Example: `ior -b 2M -t 2K -O SummaryFormat=CSV -i 3` produce.
```
access,bw(MiB/s),IOPS,Latency,block(KiB),xfer(KiB),open(s),wr/rd(s),close(s),total(s),iter
write,436.5474,228841.8502,0.0000,2048.0000,2.0000,0.0001,0.0045,0.0000,0.0046,0
read,2367.9204,1220176.2821,0.0000,2048.0000,2.0000,0.0000,0.0008,0.0000,0.0008,0
write,576.2719,297184.2374,0.0000,2048.0000,2.0000,0.0000,0.0034,0.0000,0.0035,1 …
```
=> CSV output for IOR results

src/aiori-Gfarm.c
This change updates aiori-Gfarm.c to catch up with the new aiori interface.
=> aiori-Gfarm: update to the new aiori interface

src/ior-output.c
Fixes duplicated keys (adds to JSON issue in #264)
=> JSON output. Remove duplicated keys.

src/ior.c, src/parse_options.c
This is a start to improve the random generation (see PR #219) by allowing to reproduce the random generation.
=> Enable random seed to be stored.

src/aiori-Gfarm.c
This patch is sequel to #262.  It introduces sync interface.
=> aiori-Gfarm: sequel to #262 - sync interface

src/ior-output.c, src/mdtest.c, src/utilities.c, src/utilities.h
Remove duplicated functionality between mdtest and IOR.
Refactored the ShowFileSystemSize function.
Bug was reported by Mohamad. Thx!
=> Remove duplicated functionality between mdtest and IOR.

src/aiori-S3-libs3.c, src/md-workbench.c, src/mdtest.c
=> Move option checks before inititalization.

src/mdtest.c
Implement the new --print-all-procs option for printing of individual process results.
=> Allow MDTest to print per proc.

src/aiori-S3-libs3.c
This PR gives the user the ability to specify the region and the location of the bucket.
This is useful when testing against public cloud provider. More Info can be found here:
https://docs.aws.amazon.com/AmazonS3/latest/dev/optimizing-performance-guidelines.html#optimizing-performance-guidelines-combine
=> added region and location to libs3

src/aiori-HDFS.c, src/ior.c, src/ior.h, testing/build-hdfs.sh
This patch is attempting to backport the API for #301
=> HDFS module ported to current AIORI API

src/mdtest.c
This patch outputs statistics per rank and per iteration.
=> MDTest calculate min/max/mean across iterations #300.

src/aiori-DFS.c
The SVCL argument is being removed from the DAOS API, so conditionally
compile out while maintaining backwards compatibility to versions where
it's still required.
=> dfs: conditionally compile out svcl setting

src/md-workbench.c, src/mdtest.c
Minor issues revealed using valgrind
=> Bugfix: valgrind memory issues

src/ior.c
Allows an aiori initialize function to use testComm
=> Move initialization of TestComm before aiori->initialize()

src/md-workbench.c
The implementation for the new verification was incomplete. This PR fixes it.
=> MDWorkbench: Fix new verification option

doc/sphinx/userDoc/install.rst, doc/sphinx/userDoc/tutorial.rst
for what it is worth, this PR tries to improve the reading experience ofr two pages of the documentation.
=> converting to sphinx code snippets

src/aiori-MPIIO.c, src/ior.c
- fix malloc issue with MPI-IO
- check that the proper interleaved pattern is created
=> Fix MPI-IO strided access.

src/ior-output.c, src/ior.c, src/ior.h, src/iordef.h, src/md-workbench.c, src/mdtest.c, src/parse_options.c, src/utilities.c, src/utilities.h, testing/basic-tests.sh, testing/test-lib.sh
Also, update first 8 byte element in each 4k block on updates to defy dedup.
=> Support random data generation for memory pattern in utilities. 

src/mdtest.c
Also fix a potential issue for the calculation if a test is not run (number of items = 0).
=> MDTest, support flag to show per rank performance: #357

src/ior-output.c
This pull request adds a feature to include the number of tasks in the CSV output file.
=> Adding number of tasks to the CSV output

src/aiori-S3-libs3.c
This patch adds some minor improvements to the error handling in S3-libS3 when using a single bucket for the deletion operation.
The new environment variable "S3LIB_DELETE_HEURISTICS" allows controlling at which file size of the initial fragment the list_bucket operation is executed. Otherwise for each deleted file/directory the list_bucket operation is invoked which is very inefficient. Note that S3-libs3 intends to be a "optimal"/best case performance for S3 anyway.
=> S3-libs3 error handling improved, added a heuristic for testing as well.

src/aiori-POSIX.c
=> AIORI POSIX use open flag. #363

src/aiori-S3-libs3.c, src/mdtest.c
Also, allow to output verification errors.
=> Bugfix in AIORI-S3-libs3 to prevent name collisions. 

src/aiori-DFS.c, src/utilities.c
- better init/fini logic
- make errors non-fatal and update IO error to look like POSIX driver
- update parent dir lookup hash
- add dfs_rename
=> aiori/DFS: several enhancements and cleanup to DFS driver

src/aiori-DFS.c
- if a user explicitly specifies an invalid object class for files or dirs, fail instead of using the default to avoid confusion.
- abort if user is using DFS and init of DFS driver fails since IOR does not check init rc and can cause segfaults later.
=> aiori-dfs: fail when object class specified is not valid

src/aiori-NCMPI.c
This PR updates the NCMPI option to use the PnetCDF APIs.
=> PnetCDF update

src/utilities.c
Fixing resource leaks in utilities.c
=> Fixing resource leaks in utilities.c

src/utilities.c
The API wasn't that well-implemented unfortunately. Also, optimized performance slightly.
=> Bugfixing the non-reproducible memory pattern for random with mdworkbench

src/ior.c
While digging around the timing path, I didn't like the magic number indexes.  I don't think it's likely that this timer array will grow but at least the intent becomes a bit more clearer than using raw indexes.
=> human readable timer indexes

configure.ac, src/Makefile.am, src/aiori-POSIX.c, src/ior.c, src/ior.h, src/iordef.h, src/md-workbench.c, src/mdtest.c, src/parse_options.c, src/utilities-gpu.cu, src/utilities.c, src/utilities.h
=> Fix cufile

configure.ac, src/Makefile.am, src/ior-output.c, src/ior.c, src/iordef.h, src/parse_options.c, src/utilities-gpu.cu, src/utilities.c, src/utilities.h
This PR will include additional options for testing with CUDA.
=> CUDA timestamp verification.

doc/mdtest.1, src/mdtest.c
Makes the mdtest units explicit for new users like me :)
Also resolves https://github.com/hpc/ior/issues/452
=> Add units to mdtest

src/aiori-DFS.c
I'd appreciate @mchaarawi reviewing these changes -- I kind of just smashed things around until the warnings (gcc-11.2.0 on sunspot against DAOS-2.2 ) went away.
=> Daos warning fixes

src/aiori-DFS.c
@mchaarawi or @roblatham00, could you test this using DAOS to ensure that these DAOS patches got pulled into the 4.0 release branch correctly?  I want to cut a stable 4.0 release, but I also want it to works with DAOS as it exists today.
=> Pull DAOS fixes into 4.0 release stream

src/aiori-MPIIO.c
In the single shared file case, there is no need for all ranks to query the file size; only a single rank can do that and bcast the result to others.
=> aiori/mpiio: optimize get size by issuing only on 1 rank

configure.ac
See https://github.com/IO500/io500/issues/67#issuecomment-2809099643
=> Automake macro update to 2.71 - Io500 fix #67

src/aiori-MPIIO.c, src/ior.c, src/ior.h, src/utilities.c, src/utilities.h
See https://github.com/IO500/io500/issues/88#issuecomment-2869874292
=> Attempt for 64 Bit rand.
